/**
 * Phase 11 T11-3 — Playwright E2E fixtures.
 *
 * The MSW browser worker (generated by `npx msw init public/`) intercepts
 * /v1/* and /healthz from the browser. We register it via Playwright's
 * `use.addInitScript` so the worker is alive BEFORE the app's React tree
 * mounts and issues its first fetch — without this, the first request races
 * with worker startup and bypasses the mock.
 *
 * The handlers under `src/mocks/browser.ts` (T11-3) use the same wildcard-host
 * patterns in both browser (here) and node (vitest) environments, so the
 * wire-format contract is the single source of truth.
 */
import { test as base, expect } from "@playwright/test";

export const test = base.extend({
  page: async ({ page }, use) => {
    // Inject the MSW service worker registration before any page script runs.
    // The `?init` query string avoids the React app's MSW gate (which is
    // off in production mode); we always start the worker in E2E.
    await page.addInitScript(async () => {
      const mod = (await import("/mockServiceWorker.js")) as {
        worker: { start: (opts?: unknown) => Promise<void> };
      };
      await mod.worker.start({ onUnhandledRequest: "bypass" });
    });
    await use(page);
  },
});

export { expect };
